[package]
name = "mediawiki"
description = "A MediaWiki client library"
keywords = ["MediaWiki","API"]
categories = ["api-bindings","authentication"]
license = "MIT/Apache-2.0"
repository = "https://github.com/magnusmanske/mediawiki_rust"
version = "0.1.28"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
time = "=0.2.7"
serde_json = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
user_agent = "0.9"
urlencoding = "1"
config = "0.10"
cookie = "0.13"
lazy_static = "1.4"
nanoid = "0.3.0"
url = "2.1"
base64 = "0.11"
hmac = "0.7.1"
sha-1 = "0.8.2"
